### PR TITLE
Added new tutorial for ipa_driver

### PR DESCRIPTION
**Pull request by ipa-jsf**
I wil clean up the massive amount of files later on. Promises!

### CODE REVIEW

**Comment by ipa-jsf** [comment]
The binary files will be removed after the tutorial. Right now, I do not want to risk deleting too much

**Comment by ipa-goa** [comment]
Please remove all unneeded files (931!!) now. It will blow up the size of the repository if we leave them because they will always be in the history.

**Comment by ipa-jsf** [comment]
Removed all unnecessary files I've found

**Comment by floweisshardt** [comment]
I still have 360 Files in thie PR containing temporary files, automatic generated files, binaries, ...

I'll close that PR without merging, please cleanup first. (please do **not** "git rm " the binary files, but remove them from history too, otherwise the size of the repository will blow up anyway as @ipa-goa mentioned).

**Pull request closed without merging**
